name: Build Tentacles
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Clone paperweight
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: "1.2.x"
          owner: "GrapheneMC-dev"
          repository: "paperweight"
      - name: Setup paperweight
        run: |
          cd paperweight
          ./gradlew publishToMavenLocal
          cd ..
      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: |
          ./gradlew build --stacktrace
          ./gradlew paperclipJar --stacktrace
      - name: Archive Paperclip
        uses: actions/upload-artifact@v4
        with:
          name: Graphene
          path: build/libs/Graphene-1.17.1-R0.1-SNAPSHOT.jar
